# Generated by Django 3.0.6 on 2020-05-05 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Phones', 'Phoness'), ('Books', 'Books'), ('Fashion', 'Fashion'), ('Technology Gadgets', 'Technology Gadgets'), ('Electronics', 'Electronics')], max_length=200, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Out for Delivery', 'Out for Delivery'), ('Pending', 'Pending')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Product')),
            ],
        ),
    ]
